server:
  port: 10090

spring:
  application:
    name: usgp-servicedemo
  zipkin:
    base-url: http://localhost:23000
    enabled: true
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: usgp-config
      label: master
#      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true

local:
  nickname: kyobighead.fcbjguoan222
